In [51]:
#MATRIX MULTIPLICATION

In [52]:
import numpy as np

def matrix_multiplication(mat_A, mat_B):
    #Get dimensions
    row_A, col_A = len(mat_A), len(mat_A[0])
    row_B, col_B = len(mat_B), len(mat_B[0])

    #Validate rows and columns
    if col_A != row_B: 
        raise ValueError("The matrices should be in m x n and n x p to perform operation")

    # Initiallize matrix
    result = [[0 for c in range(col_B)]for r in range(row_A)]

    # Matrix multiplication

    for i in range(row_A):
        for j in range(col_B):
            for k in range(row_B):
                result[i][j] += mat_A[i][k] * mat_B[k][j]

    return result
                
    

In [53]:
A = np.arange(1,11).reshape(5, 2)
B = np.arange(20,26).reshape(2, 3)

try:
    print(matrix_multiplication(A, B))
except ValueError as e:
    print(e)


[[np.int64(66), np.int64(69), np.int64(72)], [np.int64(152), np.int64(159), np.int64(166)], [np.int64(238), np.int64(249), np.int64(260)], [np.int64(324), np.int64(339), np.int64(354)], [np.int64(410), np.int64(429), np.int64(448)]]


In [54]:
# MATRIX ADDITION

In [55]:
def matrix_addition(mat_A, mat_B):
    row_A, col_A = len(mat_A), len(mat_A[0])
    row_B, col_B = len(mat_A), len(mat_A[0])

    # Check for conditions
    if row_A != row_B or col_A != col_B:
        raise ValueError("The shape of the matrix should be equal")

    # Initialilze matrix
    result = [[0 for j in range(col_A)] for i in range(row_A)]
    
    # Perform Addition 
    for i in range(row_A):
        for j in range(col_A):
            result[i][j] = int(mat_A[i][j] + mat_B[i][j])

    return result

In [56]:
A = np.arange(1,11).reshape(5, 2)
B = np.arange(20,30).reshape(5, 2)

try:
    A_add_B = matrix_addition(A, B)
    for row in A_add_B:
        print(*row)
except ValueError as e:
    print(e)



21 23
25 27
29 31
33 35
37 39


In [57]:
#TRANSPOSE MATRIX 

In [58]:
def transpose(matrix):
    row, col = len(matrix), len(matrix[0])
    transpose = np.zeros((col, row)) 
    for i in range(row):
        for j in range(col):
            transpose[j][i] = matrix[i][j]
    return transpose

In [59]:
print(A)
tr = transpose(A)
print(tr)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[[ 1.  3.  5.  7.  9.]
 [ 2.  4.  6.  8. 10.]]


In [60]:
# Square matrix

In [61]:
def isSquare(matrix):
    return all(len(row) == len(matrix) for row in matrix)

In [62]:
# Matrix Determinant

In [63]:
def determinant(matrix):

    # Check for square matrix
    if not isSquare(matrix):
        raise ValueError("The matrix should be square")
    
    # Base 1x1 matrix
    if len(matrix) == 1:
        return matrix[0][0]

    # Base 2x2 matrix
    if len(matrix) == 2:
        return (matrix[0][0] * matrix[1][1]) - (matrix[0][1] * matrix[1][0])

    # Calculate determinant for larger matrices
    det = 0

    for i in range(len(matrix)):
        sub_mat = [row[:i] + row[i+1:] for row in matrix[1:]]
        det += ((-1) ** i) * matrix[0][i] * determinant(sub_mat)

    return det
         

In [64]:
matrix = [
    [1, 2, 3],
    [4, 7, 6],
    [7, 8, 9]
]
try:
    print(determinant(matrix))
except ValueError as e:
    print(e)

-24


In [65]:
import numpy as np
np.linalg.det(matrix)

np.float64(-24.000000000000004)

In [66]:
# Identity Matrix

In [67]:
def identity(size):
    return [[1 if i == j else 0 for j in range(size)] for i in range(size)]

In [68]:
# Cofactor matrix

In [69]:
def cofactor(matrix):
    cofactor =  np.zeros_like(matrix)
    for i in range(len(matrix)):
        for j in range(len(matrix)):
            minor = [
                [row[c] for c in range(len(matrix)) if c!=j]
                for r, row in enumerate(matrix) if r!=i
            ]
            cofactor[i][j] = ((-1) ** (i + j)) * determinant(minor)

    return cofactor


In [70]:
cofactor(matrix)

array([[ 15,   6, -17],
       [  6, -12,   6],
       [ -9,   6,  -1]])

In [71]:
transpose(cofactor(matrix))

array([[ 15.,   6.,  -9.],
       [  6., -12.,   6.],
       [-17.,   6.,  -1.]])

In [72]:
inv = (determinant(matrix) ** -1) * transpose(cofactor(matrix))
inv

array([[-0.625     , -0.25      ,  0.375     ],
       [-0.25      ,  0.5       , -0.25      ],
       [ 0.70833333, -0.25      ,  0.04166667]])

In [73]:
matrix_multiplication(matrix, inv)

[[np.float64(1.0), np.float64(0.0), np.float64(0.0)],
 [np.float64(0.0), np.float64(1.0), np.float64(0.0)],
 [np.float64(-8.881784197001252e-16), np.float64(0.0), np.float64(1.0)]]

In [74]:
matrix

[[1, 2, 3], [4, 7, 6], [7, 8, 9]]

In [75]:
matrix = [
    [1, 2, 3],
    [4, 7, 6],
    [7, 8, 9]
]

det = determinant(matrix)
adj = transpose(cofactor(matrix))
inv = scalar_multiplication(adj, det ** -1)
matrix_multiplication(inv, matrix) 
inv


NameError: name 'scalar_multiplication' is not defined

In [ ]:
identity(5)

In [ ]:
[1, 2, 3] + [2, 3, 4]

In [ ]:
for row in cofactor(matrix):
    print(*row)

In [ ]:
inv(matrix)

In [ ]:
def det(mat):
    if len(mat) == 1:
        return mat[0][0]
    
    if len(mat) == 2:
        return (mat[0][0] * mat[1][1]) - (mat[0][1] * mat[1][0])

    determinant = 0.0

    for i in range(len(mat)):
        minor = [row[:i] + row[i+1] for row in mat[1:]]
        determinant += ((-1) ** i) * mat[0][i] * det(minor)

    return determinant


def cofactor(mat):
    cof = [[0.0 for _ in range(len(mat))] for _ in range(len(mat))]
    for i in range(len(mat)):
        for j in range(len(mat)):
            minor = [
                [r[c] for c in range(len(mat)) if c != j]
                for ind, r in enumerate(mat) if ind != i
            ]

            cof[i][j] = ((-1) ** (i + j)) * det(minor)

    return cof

In [ ]:

# MATRIX MULTIPLICATION

def matrix_multiplication(mat_A, mat_B):
    #Get dimensions
    row_A, col_A = len(mat_A), len(mat_A[0])
    row_B, col_B = len(mat_B), len(mat_B[0])

    #Validate rows and columns
    if col_A != row_B: 
        raise ValueError("The matrices should be in m x n and n x y to perform operation")

    # Initiallize matrix
    result = [[0.0 for c in range(col_B)]for r in range(row_A)]

    # Matrix multiplication

    for i in range(row_A):
        for j in range(col_B):
            for k in range(col_A):
                result[i][j] += mat_A[i][k] * mat_B[k][j]

    return result



#MATRIX ADDITTION

def matrix_addition(mat_A, mat_B):
    row_A, col_A = len(mat_A), len(mat_A[0])
    row_B, col_B = len(mat_B), len(mat_B[0])

    # Check for conditions
    if row_A != row_B or col_A != col_B:
        raise ValueError("The shape of the matrix should be equal")

    # Initialilze matrix
    result = [[0.0 for j in range(col_A)] for i in range(row_A)]
    
    # Perform Addition 
    for i in range(row_A):
        for j in range(col_A):
            result[i][j] = int(mat_A[i][j] + mat_B[i][j])

    return result


#TRANSPOSE MATRIX

def transpose(matrix):
    row, col = len(matrix), len(matrix[0])
    transpose = [[0.0 for _ in range(row)]for _ in range(col)] 
    for i in range(row):
        for j in range(col):
            transpose[j][i] = float(matrix[i][j])
    return transpose


# SQUARE MATRIX

def isSquare(matrix):
    return all(len(row) == len(matrix) for row in matrix)

    

# MATRIX DETERMINANT

def determinant(matrix):

    # Check for square matrix
    if not isSquare(matrix):
        raise ValueError("The matrix should be square")
    
    # Base 1x1 matrix
    if len(matrix) == 1:
        return matrix[0][0]

    # Base 2x2 matrix
    if len(matrix) == 2:
        return (matrix[0][0] * matrix[1][1]) - (matrix[0][1] * matrix[1][0])

    # Calculate determinant for larger matrices
    det = 0.0

    for i in range(len(matrix)):
        sub_mat = [row[:i] + row[i+1:] for row in matrix[1:]]
        det += ((-1) ** i) * matrix[0][i] * determinant(sub_mat)

    return det


# IDENTITY MATRIX

def identity(size):
    return [[1 if i == j else 0 for j in range(size)] for i in range(size)]



#COFACTOR MATRIX

def cofactor(matrix):
    cofactor =  [[0.0 for _ in range(len(matrix))] for _ in range(len(matrix))]
    for i in range(len(matrix)):
        for j in range(len(matrix)):
            minor = [
                [row[c] for c in range(len(matrix)) if c!=j]
                for r, row in enumerate(matrix) if r!=i
            ]
            cofactor[i][j] = ((-1) ** (i + j)) * determinant(minor)

    return cofactor


# SCALAR MULTIPLICATION

def scalar_multiplication(matrix, scalar):
    row, col = len(matrix), len(matrix[0])
    mul_mat = [[0 for _ in range(col)] for _ in range(row)]
    for i in range(row):
        for j in range(col):
            mul_mat[i][j] = matrix[i][j] * scalar

    return mul_mat


#INVERSE MATRIX

def inv(matrix):
    
    adj = transpose(cofactor(matrix))
    inv = scalar_multiplication(adj, (1 / determinant(matrix)))
    return inv

In [ ]:
A = [
    [1,2,3],
    [2,3,5],
    [3,4,5]
]
for _ in matrix_multiplication(inv(A), A):
    print(_)

In [ ]:
def mat_mul(A, B):
    row_A, col_A = len(A), len(A[0])
    row_B, col_B = len(B), len(B[0])

    if (col_A != row_B):
        raise ValueError("The matrices should be in m x n and n x y to perform operation")

    result = [[0.0 for c in col_B] for r in row_A]

    for i in range(row_A):
        for j in range(col_B):
            for k in range(row_B):
                result[i][j] += A[i][k] * B[k][j]

    return result

def det(A):
    
    if not all(len(r) == len(A) for r in A):
        raise ValueError("The matrix should be square")

    if len(A) == 1:
        return A[0][0]

    if len(A) == 2:
        return (A[0][0] * A[1][1]) - (A[0][1] * A[1][0])

    deter = 0.0

    for i in range(len(A)):
        minor = [r[ : i] + r[i+1 : ] for r in A[1 : ]]
        deter += ((-1) ** i) * A[0][i] * det(minor)

    return deter

In [ ]:
import numpy as np
rng = np.random.default_rng(seed = 42)
matrix = rng.integers(low = 0, high = 10000, size = 10000).reshape(100,100)
det(matrix.tolist())

In [ ]:
import numpy as np

def gradient_descent(x_values, y_values, learning_rate=0.08, iterations=1000):
    x_values = np.array(x_values)
    y_values = np.array(y_values)

    slope = 0.0
    intercept = 0.0
    n = len(x_values)

    for i in range(iterations):
        # predictions
        y_predictions = slope * x_values + intercept

        # cost 
        cost = np.mean((y_values - y_predictions) ** 2)

        # gradients
        slope_gradient = -(2 / n) * np.sum(x_values * (y_values - y_predictions))
        intercept_gradient = -(2 / n) * np.sum(y_values - y_predictions)

        # update parameters
        slope -= learning_rate * slope_gradient
        intercept -= learning_rate * intercept_gradient

        # print progress
        print(f"Iteration {i}: cost={cost:.4f}, slope={slope:.4f}, intercept={intercept:.4f}")

    return slope, intercept


In [ ]:
a = [1,2,3]
b = [5,2,1]
slope, intercept = gradient_descent(a, b)
print("Final slope:", slope)
print("Final intercept:", intercept)


In [ ]:
def grad(x_values, y_values, learning_rate=0.08, iterations=1000):
    x_values = np.array(x_values)
    y_values = np.array(y_values)

    slope = 0.0
    intercept =0.0
    n = len(x_values)

    for i in range(iterations):

        y_predictions = slope * x_values + intercept

        cost = np.mean((y_values - y_predictions) ** 2 )

        slope_gradient = -(2/n) * np.sum(x_values * (y_values - y_predictions))
        intercept_gradient = -(2/n) * np.sum(y_values - y_predictions)

        slope -= learning_rate * slope_gradient
        intercept -= learning_rate * intercept_gradient

    return slope, intercept 
                                             
    

In [ ]:
import numpy as np
import matplotlib.pyplot as plt


x = [1, 2, 3, 4, 5]
y = [3, 4, 2, 5, 6]

slope, intercept = grad(x, y,learning_rate = 0.001, iterations = 10000)

print("Slope:", slope)
print("Intercept:", intercept)

x_new = np.array([1, 2, 3, 4, 5 ])
y_pred = slope * x_new + intercept

plt.scatter(x, y, color="blue", label="Data points")
plt.plot(x_new, y_pred, color="red", label="Best fit line")
plt.legend()
plt.show()


In [ ]:
A = [
    [1,2,3],
    [3,2,4],
    [5,6,4]
]

B = [
    [2,3,5],
    [1,6,2],
    [7,3,4]
]
for _ in matrix_multiplication(A, transpose(A)):
    print(_)

In [ ]:
(7 +((121) ** 0.5)) / 2

In [ ]:
mul = matrix_multiplication(A,B)
inv = inv(B)
for i in mul:
    print(i)

In [ ]:
#PCA

In [ ]:
import numpy as np
from numpy.linalg import eigh

def pca(A, k = None):
    #mean centered data
    col_mean = np.mean(A, axis = 0)
    scaled_data = A - col_mean

    #covariance
    cov_mat = np.cov(scaled_data.T)

    #eigens and sort eigens
    eigvals, eigvecs = eigh(cov_mat)
    sort_idx = np.argsort(eigvals)[::-1]
    eigvecs = eigvecs[ : , sort_idx]
    eigvals = eigvals[sort_idx]

    #reduce dimensions
    if k is not None:
        eigvecs = eigvecs[ : , : k]

    #project it to eig vector
    projected_data = scaled_data.dot(eigvecs)

    return projected_data, eigvals, eigvecs
    


In [ ]:

np.random.seed(42)
X = np.random.randn(100, 3)  
projected, eigvals, eigvecs = pca(X, k=2)

print("Projected data shape:", projected.shape)
print("Eigenvalues:", eigvals)
print("Eigenvectors:\n", eigvecs)



In [ ]:
import matplotlib.pyplot as plt

plt.scatter(projected[:, 0], projected[:, 1])
plt.xlabel("PC1")
plt.ylabel("PC2")
plt.title("PCA Projection")
plt.show()
