In [1]:
import numpy as np

In [2]:
# Create a 1-D NumPy array of all even integers from 2 to 20 (inclusive).

In [3]:
np.arange(2,21,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [4]:
np.linspace(2, 20, 10, dtype=np.int64)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [5]:
# Create a 2×3 NumPy array filled with zeros, then change the middle element (row=0, col=1) to 7. Print the updated array.

In [6]:
zero = np.zeros((2,3), dtype=int)
zero[0,1] = 7

In [7]:
zero

array([[0, 7, 0],
       [0, 0, 0]])

In [8]:
# Take the 3×4 matrix from the previous question. 
# Extract all elements from the second row and print them as a 1-D array.

In [9]:
arr = np.arange(1, 13).reshape(3, 4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [10]:
arr[1]

array([5, 6, 7, 8])

In [11]:
# From the same 3×4 array, extract the third column (all rows, column index 2). Print it as a 1-D array.

In [12]:
arr[:, 2]

array([ 3,  7, 11])

In [13]:
# Take the same 3×4 array. 
# Extract the submatrix consisting of the last two rows and the last two columns. Print the result.

In [14]:
arr[-2:, -2:]

array([[ 7,  8],
       [11, 12]])

In [15]:
# Generate a 4×4 identity matrix (1’s on the diagonal, 0’s elsewhere). 
# Then multiply every element by 5. Print the result.

In [16]:
identity = np.eye(4, dtype=int)
identity

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [17]:
identity*5

array([[5, 0, 0, 0],
       [0, 5, 0, 0],
       [0, 0, 5, 0],
       [0, 0, 0, 5]])

In [18]:
identity

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [19]:
# Create a NumPy array of shape (3,3) filled with values from 1 to 9. 
# Then compute the sum of each column. Print the result as a 1-D array.

In [20]:
arr = np.arange(1,10).reshape(3,3)
arr.sum(axis = 0)

array([12, 15, 18])

In [21]:
# Given a 1-D array a = np.array([1, 2, 3, 4, 5]), 
# use boolean indexing to replace all values greater than 3 with 0`. 
# Print the modified array.

In [22]:
a = np.array([1, 2, 3, 4, 5])
mask = a > 3
a[ mask ] = 0
a

array([1, 2, 3, 0, 0])

In [23]:
# Create a 1-D array x = np.array([1.0, 2.0, 3.0]) and a 1-D array y = np.array([10.0, 20.0, 30.0]). 
# Use broadcasting to compute x + y and x[:, None] * y (outer product). 
# Print both results and their shapes.

In [24]:
x = np.array([1.0, 2.0, 3.0])
y = np.array([10.0, 20.0, 30.0])
total = x + y
result = x[:, None]*y
print(f"{total}\n Shape is : {total.shape}")
print(f"{result}\n Shape is : {result.shape}")

[11. 22. 33.]
 Shape is : (3,)
[[10. 20. 30.]
 [20. 40. 60.]
 [30. 60. 90.]]
 Shape is : (3, 3)


In [25]:
np.outer(x,y)

array([[10., 20., 30.],
       [20., 40., 60.],
       [30., 60., 90.]])

In [26]:
result

array([[10., 20., 30.],
       [20., 40., 60.],
       [30., 60., 90.]])

In [27]:
# Set a random seed for reproducibility, then generate a 2×3 array of standard normal values. 
# Compute the mean of each column and the overall standard deviation. Print both results.


In [28]:
np.random.seed(32)
matrix = np.random.randn(2, 3)
mean = matrix.mean(axis = 0)
sd = matrix.std()
print(f"Mean of each column : {mean} \n Standard deviation : {sd}")

Mean of each column : [-0.13930501  0.88061805  0.58144079] 
 Standard deviation : 0.4488118117912318


In [29]:
matrix

array([[-0.34889445,  0.98370343,  0.58092283],
       [ 0.07028444,  0.77753268,  0.58195875]])

In [30]:
# Using np.random.default_rng(123), generate a 1-D array of 10 integers from 0 to 99 (inclusive). 
# Replace all values less than 50 with their square, and values ≥50 with -1. 
# Print the final array and its dtype.

In [31]:
import numpy as np
rng = np.random.default_rng(0)
arr = rng.integers(0, 100, size = 10)
# np.where( arr < 50, arr ** 2, -1)
arr[arr < 50] = arr[arr < 50] ** 2
arr[arr >= 50] = -1
arr

array([-1, -1, -1, -1, -1, 16, 49,  1, -1, -1])

In [32]:
# Create a large 1-D array x of 1,000,000 random floats in [0,1) using default_rng(0).random(1_000_000). 
# Compute the sum in three ways and time them: Python loop, np.sum, and x @ np.ones_like(x). 
# Print the times and confirm all sums match within atol=1e-93

In [33]:
import time
arr = rng.random(1000000)
sum1 = 0
#---------Python Loop----------
t1_start = time.time()
sum1 = 0
for i in arr:
    sum1 += i
t1_end = time.time()


#---------np.sum----------------
t2_start = time.time()
sum2 = np.sum(arr)
t2_end = time.time()


#--------Dot product------------
t3_start = time.time()
sum3 = arr @ np.ones_like(arr)
t3_end = time.time()


print("--------PYTHON LOOP--------")
print(f"Sum : {sum1} ")
print(f"Start time : {t1_start} \n End time : {t1_end}")

print("--------NP SUM--------")
print(f"Sum : {sum2} ")
print(f"Start time : {t2_start} \n End time : {t2_end}")

print("--------DOT PRODUCT--------")
print(f"Sum : {sum3} ")
print(f"Start time : {t3_start} \n End time : {t3_end}")


print(f"\n\n\n {np.allclose(sum1, sum2, sum3, atol = 1e-93)}")

--------PYTHON LOOP--------
Sum : 500161.34001449036 
Start time : 1763189617.842737 
 End time : 1763189617.9476142
--------NP SUM--------
Sum : 500161.3400144767 
Start time : 1763189617.9486158 
 End time : 1763189617.9512286
--------DOT PRODUCT--------
Sum : 500161.3400144768 
Start time : 1763189617.9512286 
 End time : 1763189617.9877741



 True


In [34]:
# Given a 2-D array a with shape (4,5), compute the mean of each row, then subtract the corresponding row mean from each row (mean-centering). 
# Verify each resulting row has mean≈0 within atol=1e-12. Print the centered array and the verification result.
# Targets: broadcasting, keepdims/shape alignment, np.mean(axis=1), np.allclose

In [35]:
arr = np.arange(1,21).reshape(4,5)
mean = arr.mean(axis = 1, keepdims = True)
mean_center = arr - mean
verify = np.allclose(mean_center.mean(axis=1), 0, atol = 1e-12)
print(mean_center)
print(verify)

[[-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]
 [-2. -1.  0.  1.  2.]]
True


In [36]:
# Create two arrays: a = np.array([1, 2, 0, -1, -2]) and b = np.array([0, 1, 2, 0, -2]),
# Compute the elementwise safe division a / b where division by zero returns 0 instead of inf/NaN, without using Python loops. 
# Print the result and its dtype.
# Targets: ufuncs, np.divide with where and out parameters

In [37]:
a = np.array([1, 2, 0, -1, -2])
b = np.array([0, 1, 2, 0, -2])
result = np.zeros_like(a, dtype=float)
np.divide(a, b, out=result, where=b!=0)
print(result)
print(result.dtype)

[0. 2. 0. 0. 1.]
float64


In [38]:
# Given an array x = np.array([0.0, 1.0, 2.0, np.nan, 4.0, np.inf, -np.inf]), 
# compute the elementwise logarithm base e with safe handling:

#     For x<=0 or non-finite values, return 0.

#     Otherwise return np.log(x).

# Do this without Python loops, using ufuncs and masking. Print the result and verify no NaN/inf remains.

In [39]:
x = np.array([0.0, 1.0, 2.0, np.nan, 4.0, np.inf, -np.inf])
y = np.nan_to_num(x, nan=0, posinf=0, neginf=0)
mask = (x > 0) & np.isfinite(x)
y[mask] = np.log(x[mask])
y

array([0.        , 0.        , 0.69314718, 0.        , 1.38629436,
       0.        , 0.        ])

In [40]:
# Create a 5×5 array of integers 0–24. Extract the 3×3 central view using slicing, and set its diagonal to -1 in place. 
# Verify that the changes reflect in the original array (prove it’s a view, not a copy). 
# Print both arrays.
# Targets: slicing views (not copies), in-place modification, np.diag indexing

In [41]:
matrix = np.arange(25).reshape(5, 5)
centre_matrix = matrix[1:4, 1:4]
print(matrix,"\n")
np.fill_diagonal(centre_matrix, -1)
print(matrix)
print()
print(centre_matrix)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 

[[ 0  1  2  3  4]
 [ 5 -1  7  8  9]
 [10 11 -1 13 14]
 [15 16 17 -1 19]
 [20 21 22 23 24]]

[[-1  7  8]
 [11 -1 13]
 [16 17 -1]]


In [42]:
# Create a 6×6 NumPy array with values from 0 to 35.
# Using fancy indexing (no Python loops), set all elements in a 3×3 central block to 99.
# Print the modified array.
# Verify that only those 9 positions were changed, and all other elements remain unchanged.
# Targets: fancy indexing with row/column index arrays, broadcasting behavior of indexing

In [43]:
matrix = np.arange(0,36).reshape(6, 6)
rows = [1, 3, 5]
cols = [0, 2, 4]
matrix[np.ix_(rows, cols)] = 99
print(matrix)

#----------verify------------
check = np.ones_like(matrix, dtype=bool)
check[np.ix_(rows, cols)] = False
unchanged = np.all(matrix[check] != 99)
changed = np.all(matrix[~check] == 99)
print(changed & unchanged)


[[ 0  1  2  3  4  5]
 [99  7 99  9 99 11]
 [12 13 14 15 16 17]
 [99 19 99 21 99 23]
 [24 25 26 27 28 29]
 [99 31 99 33 99 35]]
True


In [44]:
# Given a 10,000-length 1-D float array x, compute a rolling mean with window size 5 using only NumPy (no loops, no pandas). 
# Return an array of length 9,996 containing the valid-centered means. 
# Print the result’s first 5 values and its shape.

In [45]:
rng = np.random.default_rng()
x = rng.random(10000)
w_size = 5
stride = np.lib.stride_tricks.sliding_window_view(x, w_size)
rolling_mean = stride.mean(axis = 1)
print(rolling_mean[:5])
print(rolling_mean.shape)

[0.62726332 0.61067277 0.52222039 0.5523748  0.53053629]
(9996,)
