# TensorFlow


In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd

np_arr = np.array([1.0, 2.0, 3.0])

# TensorFlow Constant (Immutable Tensor)
tf_tensor_const = tf.constant([1.0, 2.0, 3.0])

# TensorFlow Variable (Mutable Tensor)
tf_tensor_var = tf.Variable([1.0, 2.0, 3.0])

In [2]:
print(np_arr)
print(tf_tensor_const)
print(tf_tensor_var)

[1. 2. 3.]
tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)
<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>


In [3]:
x = tf.Variable(3.0)

with tf.GradientTape() as tape:

    y = x**2

gradient = tape.gradient(y, x)

gradient.numpy()

np.float32(6.0)

By default, once you call tape.gradient(), the tape destroys its memory to free up RAM. If you try to call it a second time, it will crash.


In [4]:
with tf.GradientTape() as tape:

    y = x**2
    z = y**2

tape.gradient(z, [y, x])

[<tf.Tensor: shape=(), dtype=float32, numpy=18.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=108.0>]

# Keras


In [5]:
model = tf.keras.Sequential(
    [
        # Input layer
        tf.keras.layers.Input(shape=(5,)),
        # Single hidden layer with 10 neurons and ReLU activation
        tf.keras.layers.Dense(units=10, activation="relu"),
        # Output layer
        tf.keras.layers.Dense(units=1, activation="linear"),
    ]
)

model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 10)             │            60 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            11 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 71 (284.00 B)

 Trainable params: 71 (284.00 B)

 Non-trainable params: 0 (0.00 B)

In [6]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

# Sample working of the DL model using keras
X = pd.read_csv(
    r"C:\Users\USER\Desktop\student_id,study_hours,attendance,p.csv",
    index_col="student_id",
)

y = X["admitted"]
X = X.drop(columns=["admitted"])

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X_train)

tf.random.set_seed(42)

model = tf.keras.Sequential(
    [
        tf.keras.layers.Input(shape=(5,)),
        tf.keras.layers.Dense(units=8, activation="relu"),
        tf.keras.layers.Dense(units=1, activation="sigmoid"),
    ]
)

model.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])

model.fit(X_scaled, y_train, epochs=100, batch_size=10)

Epoch 1/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.4167 - loss: 0.7878  
Epoch 2/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 0s/step - accuracy: 0.3750 - loss: 0.7810  
Epoch 3/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.3333 - loss: 0.7746
Epoch 4/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.3333 - loss: 0.7684 
Epoch 5/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.3333 - loss: 0.7623 
Epoch 6/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.2917 - loss: 0.7563 
Epoch 7/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.2500 - loss: 0.7505
Epoch 8/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.2083 - loss: 0.7448 
Epoch 9/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 0s/step - accuracy: 0.2083 - loss: 0.7393  
Epoch 10/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.1667 - loss: 0.7339 
Epoch 11/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.1250 - loss: 0.7286
Epoch 12/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.0417 - lo

In [7]:
model.predict(X_train)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step


array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]], dtype=float32)

In [8]:
import tensorflow as tf


# We add this decorator to compile the function into a Graph
@tf.function
def my_graph_function(x):
    # 1. Standard Python operation
    print("PYTHON PRINT: Tracing the blueprint...")

    # 2. TensorFlow operation
    tf.print("TF PRINT: Executing the graph!")

    # 3. TensorFlow math
    return x**2


# Let's test it with a Tensor
tensor_input = tf.constant(3.0)

result1 = my_graph_function(tensor_input)  # First call
result2 = my_graph_function(tensor_input)  # Second call
result3 = my_graph_function(tensor_input)  # Third call

PYTHON PRINT: Tracing the blueprint...
TF PRINT: Executing the graph!
TF PRINT: Executing the graph!
TF PRINT: Executing the graph!


Make a custom layer that squares the input features, applies an inverse trainable linear transformation, adds a bias, and then applies an activation function.


In [9]:
from typing import Any


class SquareDivideLayer(tf.keras.layers.Layer):

    def __init__(self, activation=None, **kwargs):
        super().__init__(**kwargs)

        self.activation = tf.keras.activations.get(activation)

    def build(self, input_shape: Any) -> None:

        self.w = self.add_weight(
            shape=(input_shape[-1], input_shape[-1]),
            initializer="identity",
            name="sqdivlayer_weights",
        )
        self.b = self.add_weight(
            shape=(input_shape[-1],),
            initializer="zeros",
            name="sqdivlayer_bias",
        )

    def call(self, inputs: Any) -> Any:
        w_inv = tf.linalg.inv(self.w)
        output = tf.matmul(tf.square(inputs), w_inv) + self.b
        if self.activation:
            output = self.activation(output)
        return output

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from typing import Any, Mapping

# Sample working of the DL model using keras
X = pd.read_csv(
    r"C:\Users\USER\Desktop\student_id,study_hours,attendance,p.csv",
    index_col="student_id",
)

y = X["admitted"]
X = X.drop(columns=["admitted"])

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X_train)

tf.random.set_seed(42)

model = tf.keras.Sequential(
    [
        tf.keras.layers.Input(shape=(5,)),
        tf.keras.layers.Dense(units=8, activation="relu"),
        SquareDivideLayer(activation="tanh"),
        tf.keras.layers.Dense(units=1, activation="sigmoid"),
    ]
)


class StopAtSuccessCallback(tf.keras.callbacks.Callback):
    def on_epoch_end(
        self, epoch: int, logs: Mapping[str, Any] | None | Any = None
    ) -> None:
        if logs.get("loss") < 0.1:
            self.model.stop_training = True

tf.keras.callbacks.EarlyStopping()

model.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])

model.fit(
    X_scaled, y_train, epochs=100, batch_size=10, callbacks=[StopAtSuccessCallback()]
)


Epoch 1/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - accuracy: 0.6667 - loss: 0.6808 
Epoch 2/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6667 - loss: 0.6790 
Epoch 3/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5833 - loss: 0.6774 
Epoch 4/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5417 - loss: 0.6758 
Epoch 5/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5417 - loss: 0.6740 
Epoch 6/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5417 - loss: 0.6721 
Epoch 7/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5417 - loss: 0.6700 
Epoch 8/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.5417 - loss: 0.6678
Epoch 9/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.5417 - loss: 0.6654
Epoch 10/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5417 - loss: 0.6627 
Epoch 11/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5417 - loss: 0.6599 
Epoch 12/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 0s/step - accuracy: 0.5417 - lo

In [11]:
(model.predict(X_scaled) > 0.5).astype(int)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step


array([[1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1]])

# PyTorch


In [12]:
import torch

pt_tensor = torch.tensor([1.0, 2.0, 3.0])

if torch.cuda.is_available():
    gpu_tensor = pt_tensor.to("cuda")
    print(pt_tensor)

tensor([1., 2., 3.])


If you have Weights stored on the GPU (cuda), but your Input Data is still sitting on your CPU, and you try to multiply them together, PyTorch will immediately crash. Tensors must be on the exact same hardware device to interact.


In [13]:
# Samples

x = torch.tensor(3.0, requires_grad=True)
z = torch.tensor(2.0, requires_grad=True)
y = x**z

y.backward()
print(x.grad)

tensor(6.)


If you try to call x.numpy() on a tensor that has requires_grad=True, PyTorch will throw a loud error. It does this because it wants to protect the graph's integrity. To look at it as a NumPy array, you must explicitly detach it from the graph first using x.detach().numpy()


tensor.grad as a bucket that stores accumulated gradients.

- backward() → pours gradients into the bucket.
- grad → the current contents of the bucket.
- optimizer.zero_grad() → empties the bucket.
- Accumulation exists so that many small mini-batches can collectively behave like one huge batch without requiring huge GPU memory.


In [14]:
from typing import Any

import torch
import torch.nn as nn


class NeuralNetwork(nn.Module):
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)

        self.hidden_layer1 = nn.Linear(in_features=5, out_features=8)
        self.hidden_layer2 = nn.Linear(in_features=8, out_features=4)
        self.outpu_layer = nn.Linear(in_features=4, out_features=1)
        self.activation = nn.ReLU()

    def forward(self, x):

        x = self.hidden_layer1(x)
        x = self.hidden_layer2(x)
        x = self.activation(x)
        x = self.outpu_layer(x)

        return x


model = NeuralNetwork()


# Now the training hasn't happened yet it is just showing the result of the forward pass with random assigned weights
model(torch.tensor(X_scaled, dtype=torch.float32))

tensor([[-0.7470],
        [-0.5012],
        [-0.5090],
        [-0.6555],
        [-0.6079],
        [-0.5642],
        [-0.6479],
        [-0.4042],
        [-0.4421],
        [-0.5799],
        [-0.6764],
        [-0.5575],
        [-0.7053],
        [-0.5256],
        [-0.6643],
        [-0.4223],
        [-0.4809],
        [-0.6938],
        [-0.6194],
        [-0.7205],
        [-0.5887],
        [-0.5721],
        [-0.7672],
        [-0.6369]], grad_fn=<AddmmBackward0>)

the five stages of network learning: zeroing gradients, passing data forward, calculating the loss, passing the error backward, and updating the weights.


In [15]:
# Training Loop

optimizer = torch.optim.Adam(model.parameters(), lr=0.01)
loss_fn = nn.BCEWithLogitsLoss()

X_tensor = torch.tensor(X_scaled, dtype=torch.float32)

y_tensor = torch.tensor(y_train.values, dtype=torch.float32).reshape(-1, 1)

for epoch in range(100):
    optimizer.zero_grad()

    preds = model(X_tensor)

    loss = loss_fn(preds, y_tensor)

    loss.backward()

    optimizer.step()

    print(f"Epoch {epoch}: {loss.item():.4f}")

Epoch 0: 0.8040
Epoch 1: 0.7799
Epoch 2: 0.7591
Epoch 3: 0.7410
Epoch 4: 0.7269
Epoch 5: 0.7207
Epoch 6: 0.7151
Epoch 7: 0.7101
Epoch 8: 0.7056
Epoch 9: 0.7016
Epoch 10: 0.6979
Epoch 11: 0.6973
Epoch 12: 0.6974
Epoch 13: 0.6970
Epoch 14: 0.6965
Epoch 15: 0.6960
Epoch 16: 0.6956
Epoch 17: 0.6952
Epoch 18: 0.6948
Epoch 19: 0.6944
Epoch 20: 0.6941
Epoch 21: 0.6938
Epoch 22: 0.6935
Epoch 23: 0.6932
Epoch 24: 0.6929
Epoch 25: 0.6926
Epoch 26: 0.6924
Epoch 27: 0.6922
Epoch 28: 0.6920
Epoch 29: 0.6918
Epoch 30: 0.6916
Epoch 31: 0.6914
Epoch 32: 0.6913
Epoch 33: 0.6911
Epoch 34: 0.6910
Epoch 35: 0.6908
Epoch 36: 0.6907
Epoch 37: 0.6906
Epoch 38: 0.6905
Epoch 39: 0.6904
Epoch 40: 0.6903
Epoch 41: 0.6903
Epoch 42: 0.6902
Epoch 43: 0.6901
Epoch 44: 0.6901
Epoch 45: 0.6900
Epoch 46: 0.6900
Epoch 47: 0.6899
Epoch 48: 0.6899
Epoch 49: 0.6899
Epoch 50: 0.6898
Epoch 51: 0.6898
Epoch 52: 0.6898
Epoch 53: 0.6898
Epoch 54: 0.6898
Epoch 55: 0.6897
Epoch 56: 0.6897
Epoch 57: 0.6897
Epoch 58: 0.6897
Epoch 5

# PyTorch


In [1]:
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets
from torchvision.transforms import v2

In [2]:
traning_data = datasets.FashionMNIST(
    root="data",
    train=True,
    download=True,
    transform=v2.Compose([v2.ToImage(), v2.ToDtype(torch.float32, scale=True)]),
)

test_data = datasets.FashionMNIST(
    root="data",
    train=False,
    download=True,
    transform=v2.Compose([v2.ToImage(), v2.ToDtype(torch.float32, scale=True)]),
)

In [3]:
batch_size = 64

train_dataloader = DataLoader(traning_data, batch_size=batch_size)
test_dataloader = DataLoader(test_data, batch_size=batch_size)

for X, y in test_dataloader:

    # N : Number of images (batch size)
    # C : Number of channels
    # H : Height
    # W : Width

    print(f"Shape of X [N, C, H, W]: {X.shape}")
    print(f"Shape of y: {y.shape} {y.dtype}")
    break

Shape of X [N, C, H, W]: torch.Size([64, 1, 28, 28])
Shape of y: torch.Size([64]) torch.int64


In [4]:
from typing import Any

device = (
    torch.accelerator.current_accelerator().type
    if torch.accelerator.is_available()
    else "cpu"
)

# device = "cpu"

print(f"Using {device} device")


class NeuralNetwork(nn.Module):
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)

        self.flatten = nn.Flatten()
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(28 * 28, 512),
            nn.ReLU(),
            nn.Linear(512, 512),
            nn.ReLU(),
            nn.Linear(512, 10),
        )

    def forward(self, x):
        x = self.flatten(x)
        logits = self.linear_relu_stack(x)
        return logits


model = NeuralNetwork().to(device)

model

Using cuda device


NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)

In [5]:
loss_fn = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)


def train(model, dataloader, device, loss_fn, optimizer):
    size = len(dataloader.dataset)
    model.train()
    for batch, (X, y) in enumerate(dataloader):
        optimizer.zero_grad()

        X, y = X.to(device), y.to(device)

        preds = model(X)
        loss = loss_fn(preds, y)

        loss.backward()
        optimizer.step()

        if batch % 100 == 0:
            loss, current = loss.item(), (batch + 1) * len(X)
            print(f"loss : {loss:>7f} [{current:>5d} / {size}] ")
    if batch % 100 != 0:
        loss, current = loss.item(), (batch + 1) * len(X)
        print(f"loss : {loss:>7f} [{current:>5d} / {size}] ")


def test(model, dataloader, device, loss_fn):
    size = len(dataloader.dataset)
    num_batches = len(dataloader)
    test_loss, accurate = 0, 0
    model.eval()
    with torch.no_grad():
        for X, y in dataloader:
            X, y = X.to(device), y.to(device)

            preds = model(X)
            loss = loss_fn(preds, y)

            test_loss += loss.item()
            accurate += (preds.argmax(dim=1) == y).sum().item()
    test_loss /= num_batches
    accurate /= size
    print(
        f"Test Error :\n Avg Loss : {test_loss:>7f} | Accuracy : {100 * accurate:>0.1f}% \n"
    )


epochs = 5
for epoch in range(epochs):
    print(f"Epoch {epoch + 1} \n --------------------------------------------------")
    train(model, train_dataloader, device, loss_fn, optimizer)
    test(model, test_dataloader, device, loss_fn)

Epoch 1 
 --------------------------------------------------
loss : 2.303108 [   64 / 60000] 
loss : 0.546680 [ 6464 / 60000] 
loss : 0.380735 [12864 / 60000] 
loss : 0.521959 [19264 / 60000] 
loss : 0.453565 [25664 / 60000] 
loss : 0.442945 [32064 / 60000] 
loss : 0.376905 [38464 / 60000] 
loss : 0.530513 [44864 / 60000] 
loss : 0.463039 [51264 / 60000] 
loss : 0.527037 [57664 / 60000] 
loss : 0.364693 [30016 / 60000] 
Test Error :
 Avg Loss : 0.438404 | Accuracy : 83.6% 

Epoch 2 
 --------------------------------------------------
loss : 0.293588 [   64 / 60000] 
loss : 0.335032 [ 6464 / 60000] 
loss : 0.303356 [12864 / 60000] 
loss : 0.394463 [19264 / 60000] 
loss : 0.406671 [25664 / 60000] 
loss : 0.371915 [32064 / 60000] 
loss : 0.311593 [38464 / 60000] 
loss : 0.497641 [44864 / 60000] 
loss : 0.412447 [51264 / 60000] 
loss : 0.488477 [57664 / 60000] 
loss : 0.251470 [30016 / 60000] 
Test Error :
 Avg Loss : 0.408108 | Accuracy : 84.6% 

Epoch 3 
 --------------------------------

In [6]:
from typing import Any

import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets
from torchvision.transforms import v2

train_data = datasets.FashionMNIST(
    root="data",
    train=True,
    download=True,
    transform=v2.Compose([v2.ToImage(), v2.ToDtype(torch.float32, scale=True)]),
)
test_data = datasets.FashionMNIST(
    root="data",
    train=False,
    download=True,
    transform=v2.Compose([v2.ToImage(), v2.ToDtype(torch.float32, scale=True)]),
)

batch_size = 64
train_dataloader = DataLoader(
    train_data, batch_size=batch_size, shuffle=True, num_workers=2, pin_memory=True
)
test_dataloader = DataLoader(test_data, batch_size=batch_size, pin_memory=True)

device = (
    torch.accelerator.current_accelerator().type
    if torch.accelerator.is_available()
    else "cpu"
)


class NeuralNetwork(nn.Module):
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)

        self.flatten = nn.Flatten()
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(28 * 28, 512),
            nn.ReLU(),
            nn.Linear(512, 512),
            nn.ReLU(),
            nn.Linear(512, 10),
        )

    def forward(self, x):
        x = self.flatten(x)
        logits = self.linear_relu_stack(x)
        return logits


model = NeuralNetwork().to(device)
print(model)

loss_fn = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)


def train(model, dataloader, loss_fn, optimizer, device):
    size = len(dataloader.dataset)
    model.train()
    for batch, (X, y) in enumerate(dataloader):
        optimizer.zero_grad()

        X, y = X.to(device), y.to(device)

        preds = model(X)
        loss = loss_fn(preds, y)

        loss.backward()
        optimizer.step()

        if batch % 100 == 0:
            loss, current = loss.item(), (batch + 1) * len(X)
            print(f"Loss : {loss:.7f} [{current:>5d} / {size}]")
    if batch % 100 != 0:
        print(f"Loss : {loss:.7f} [{size} / {size}]")


def test(model, dataloader, loss_fn, device):
    batch_size = len(dataloader)
    size = len(dataloader.dataset)
    test_loss, accurate = 0, 0
    model.eval()
    with torch.no_grad():
        for X, y in dataloader:
            X, y = X.to(device), y.to(device)

            preds = model(X)
            loss = loss_fn(preds, y)

            test_loss += loss.item()
            accurate += (preds.argmax(dim=1) == y).sum().item()
    test_loss /= batch_size
    accurate /= size
    print(
        f"Test Error :\n Avg Loss : {test_loss:>0.7f} | Accuracy : {100*accurate:>0.1f}%\n"
    )


epochs = 10
for epoch in range(epochs):
    print(f"Epoch {epoch+1}\n----------------------------------------------------")
    train(model, train_dataloader, loss_fn, optimizer, device)
    test(model, test_dataloader, loss_fn, device)

NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)
Epoch 1
----------------------------------------------------
Loss : 2.2987187 [   64 / 60000]
Loss : 0.6464746 [ 6464 / 60000]
Loss : 0.7928845 [12864 / 60000]
Loss : 0.4051157 [19264 / 60000]
Loss : 0.5351864 [25664 / 60000]
Loss : 0.3782918 [32064 / 60000]
Loss : 0.5293205 [38464 / 60000]
Loss : 0.3960053 [44864 / 60000]
Loss : 0.3003954 [51264 / 60000]
Loss : 0.6217849 [57664 / 60000]
Loss : 0.3815477 [60000 / 60000]
Test Error :
 Avg Loss : 0.4332261 | Accuracy : 84.3%

Epoch 2
----------------------------------------------------
Loss : 0.2962123 [   64 / 60000]
Loss : 0.3223580 [ 6464 / 60000]
Loss : 0.2988658 [12864 / 60000]
Loss : 0.4650269 [19264 / 60000]
Loss : 0.

In [7]:
import pandas as pd
import torch

from sklearn.model_selection import train_test_split
from torch.utils.data import TensorDataset, DataLoader

df = pd.read_csv(
    r"C:\Users\USER\Desktop\code\inst_classfication\dataset\processed_data\audio_features.csv"
)

df = df.drop_duplicates()
df = df.iloc[:, 1:]

label_map = {
    "flute": 0,
    "guitar": 1,
    "piano": 2,
    "speech": 3,
    "violin": 4,
}

X = df.iloc[:, :-1].values
y = df.iloc[:, -1].map(label_map).astype("int64").values

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)


X_train = torch.tensor(X_train, dtype=torch.float32)
y_train = torch.tensor(y_train, dtype=torch.long)

X_test = torch.tensor(X_test, dtype=torch.float32)
y_test = torch.tensor(y_test, dtype=torch.long)

train_dataset = TensorDataset(X_train, y_train)
test_dataset = TensorDataset(X_test, y_test)

batch_size = 32
train_loader = DataLoader(
    train_dataset, batch_size=batch_size, shuffle=True, num_workers=2, pin_memory=True
)
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)

In [8]:
X.shape

(2312, 30)

In [9]:
device = (
    torch.accelerator.current_accelerator().type
    if torch.accelerator.is_available()
    else "cpu"
)


class AudioNeuralNetwork(nn.Module):
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)

        self.linear_relu_stack = nn.Sequential(
            nn.Linear(30, 512),
            nn.LeakyReLU(),
            nn.Linear(512, 512),
            nn.LeakyReLU(),
            nn.Linear(512, 256),
            nn.LeakyReLU(),
            nn.Linear(256, 5),
        )

    def forward(self, x):
        logits = self.linear_relu_stack(x)
        return logits


model = AudioNeuralNetwork().to(device)
print(model)

loss_fn = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)


def train(model, dataloader, loss_fn, optimizer, device):
    size = len(dataloader.dataset)
    model.train()
    for batch, (X, y) in enumerate(dataloader):
        optimizer.zero_grad()

        X, y = X.to(device), y.to(device)

        preds = model(X)
        loss = loss_fn(preds, y)

        loss.backward()
        optimizer.step()

        if batch % 40 == 0:
            loss, current = loss.item(), (batch + 1) * len(X)
            print(f"Loss : {loss:.7f} [{current:>5d} / {size}]")
    if batch % 40 != 0:
        print(f"Loss : {loss:.7f} [{size} / {size}]")


def test(model, dataloader, loss_fn, device):
    batch_size = len(dataloader)
    size = len(dataloader.dataset)
    test_loss, accurate = 0, 0
    model.eval()
    with torch.no_grad():
        for X, y in dataloader:
            X, y = X.to(device), y.to(device)

            preds = model(X)
            loss = loss_fn(preds, y)

            test_loss += loss.item()
            accurate += (preds.argmax(dim=1) == y).sum().item()
    test_loss /= batch_size
    accurate /= size
    print(
        f"Test Error :\n Avg Loss : {test_loss:>0.7f} | Accuracy : {100*accurate:>0.1f}%\n"
    )


epochs = 30
for epoch in range(epochs):
    print(f"Epoch {epoch+1}\n----------------------------------------------------")
    train(model, train_loader, loss_fn, optimizer, device)
    test(model, test_loader, loss_fn, device)

AudioNeuralNetwork(
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=30, out_features=512, bias=True)
    (1): LeakyReLU(negative_slope=0.01)
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): LeakyReLU(negative_slope=0.01)
    (4): Linear(in_features=512, out_features=256, bias=True)
    (5): LeakyReLU(negative_slope=0.01)
    (6): Linear(in_features=256, out_features=5, bias=True)
  )
)
Epoch 1
----------------------------------------------------
Loss : 8.7379684 [   32 / 1849]
Loss : 2.0473351 [ 1312 / 1849]
Loss : 1.5772427 [1849 / 1849]
Test Error :
 Avg Loss : 1.2591917 | Accuracy : 46.2%

Epoch 2
----------------------------------------------------
Loss : 1.1447859 [   32 / 1849]
Loss : 1.1071167 [ 1312 / 1849]
Loss : 1.6142478 [1849 / 1849]
Test Error :
 Avg Loss : 1.2234768 | Accuracy : 57.5%

Epoch 3
----------------------------------------------------
Loss : 1.1870764 [   32 / 1849]
Loss : 1.0454676 [ 1312 / 1849]
Loss : 0.9681146 [1849 / 18

In [10]:
import torch

x = torch.tensor(2.0, requires_grad=True)

y = x**2
y.backward()

print(x.grad)
y = x**2
y.backward()

print(x.grad)

tensor(4.)
tensor(8.)


# Review